# Generated by Django 3.0.6 on 2020-06-16 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0003_auto_20200616_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='target_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='target date'),
            preserve_default=False,
        ),
    ]
