# Generated by Django 3.0.6 on 2020-06-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('togobi', '0004_content_target_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='c_type',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='user',
        ),
        migrations.AlterField(
            model_name='content',
            name='target_date',
            field=models.DateTimeField(null=True, verbose_name='target date'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Plan'),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='CardType',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='UserCard',
        ),
    ]
