# Generated by Django 3.0.6 on 2020-10-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0006_auto_20201022_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
