# Generated by Django 3.0.6 on 2020-12-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0009_contentjoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentjoin',
            name='accepted_date',
            field=models.DateTimeField(null=True, verbose_name='date accepted'),
        ),
    ]
