# Generated by Django 3.0.6 on 2020-12-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0010_auto_20201213_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentjoin',
            name='status',
            field=models.IntegerField(),
        ),
    ]
