# Generated by Django 3.0.6 on 2021-01-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0011_auto_20201214_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='f_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contentjoin',
            name='remarks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
    ]
