# Generated by Django 3.0.6 on 2021-05-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0012_auto_20210116_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
