# Generated by Django 3.0.6 on 2021-05-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0013_auto_20210513_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentBookmark',
        ),
    ]
