# Generated by Django 3.0.6 on 2021-06-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0015_message_messagereceiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togobi.Content'),
        ),
    ]
