# Generated by Django 3.0.6 on 2021-07-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0016_auto_20210623_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_files', to='togobi.Content'),
        ),
    ]
