# Generated by Django 3.0.6 on 2021-07-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0017_auto_20210706_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='creation_step',
            field=models.IntegerField(default=1),
        ),
    ]
