# Generated by Django 3.0.6 on 2021-07-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0018_content_creation_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
