# Generated by Django 3.2 on 2022-02-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0020_auto_20210730_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentfile',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
