# Generated by Django 3.2 on 2022-03-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togobi', '0021_contentfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagereceiver',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagereceiver',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageReceiver',
        ),
    ]
