# Generated by Django 3.2 on 2022-04-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20220404_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='channel_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
