# Generated by Django 3.2 on 2022-04-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_dialogue_channel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialogue',
            old_name='channel_name',
            new_name='room_group_name',
        ),
    ]
