# Generated by Django 3.2 on 2022-04-07 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20220407_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomgroupuser',
            name='room_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_group_users', to='chats.roomgroup'),
        ),
    ]
