# Generated by Django 3.2 on 2022-04-07 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0006_alter_roomgroupuser_room_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomGroupRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='allowed', max_length=200)),
                ('room_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_group_restrictions', to='chats.roomgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
