# Generated by Django 3.2 on 2022-04-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_roomgrouprestriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomgroupuser',
            name='status',
            field=models.CharField(default='allowed', max_length=200),
        ),
        migrations.DeleteModel(
            name='RoomGroupRestriction',
        ),
    ]
