# Generated by Django 3.2 on 2022-04-07 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0008_auto_20220407_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(default='allow all', max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
